eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
app:
  hello: From common dev
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
