server:
  port: ${CONFIG_SERVER_PORT}
spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_SERVER_URI}
          username: ${GITLAB_USERNAME}
          password: ${GITLAB_PASSWORD}
          search-paths: ${GITLAB_SEARCH_PATHS}